development:
  adapter: postgresql
  encoding: unicode
  database: rails-uuid_as_primary_key_development
  pool: 5
  username: amorphid
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: rails-uuid_as_primary_key_testing
  pool: 5
  username: amorphid
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: rails-uuid_as_primary_key_production
  pool: 5
  username: amorphid
  password:
